steps:
# Copy environment variables
- name: 'gcr.io/cloud-builders/npm'
  dir: connector/
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "PRIVATE_KEY: $$PRIVATE_KEY"
  id: 'copy-env-variables'
  waitFor: ['-'] # The '-' indicates that this step begin immediately
  secretEnv: ['PRIVATE_KEY']

availableSecrets:
  secretManager:
  - versionName: projects/sumit-solutions/secrets/PRIVATE_KEY/versions/latest
    env: 'PRIVATE_KEY'

# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: 
#     [
#       'push', 
#       'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA'
#     ]
#   id: 'push-image-to-container-registry'
#   waitFor: ['build-image-${_IMAGE_NAME}'] # The push start once build is done

# # Deploy container image to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     [
#       'run',
#       'deploy',
#       '${_IMAGE_NAME}',
#       '--image',
#       'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA',
#       '--region',
#       'us-west2',
#       '--platform',
#       'managed',
#       '--allow-unauthenticated',
#     ]

# images:
# - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
# - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA'
# - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
